# Ignoriere VS Code Ordner
.vs/

# Ignoriere Build-Ergebnisse
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/

# NuGet-Dateien ausschließen
*.nupkg
# Die NuGet-Debug-Symbole ausschließen
*.snupkg

# Pakete ausschließen
# Es kann wünschenswert sein, diese Zeile zu kommentieren, wenn Sie NuGet-Pakete wiederherstellen möchten
# Weitere Informationen über `dotnet restore` finden Sie unter https://docs.microsoft.com/dotnet/core/tools/dotnet-restore?tabs=netcore2x
packages/

# Aktivieren Sie die folgende Zeile, um die Projektdateiänderungen zu ignorieren
# die sich aus Skripten für NuGet-Pakete ergeben.
# NuGet-Pakete in Ihrem Quellrepository zu behalten, ist normalerweise keine gute Praxis
# aber es kann in bestimmten Szenarien notwendig sein.
#project.lock.json

# MSBuild-Autogenerated-Dateien ausschließen
Microsoft.Common.CurrentVersion.targets
Microsoft.CSharp.targets

# MSTest test Results ausschließen
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

#NUnit
*.VisualState.xml
TestResult.xml
nunit-*.xml

# Build Results of an MSBuild Project
[Tt]argets/

# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/

# StyleCop
StyleCopReport.xml

# Dateien, die beim Wiederherstellen von Paketen generiert werden
Paket.Restore.targets
paket-files/

# BenchmarkDotNet-Ordner ausschließen
BenchmarkDotNet.Artifacts/

# Tooling
*.o
*.h
*.g.cpp
*.g.h
*.wixpdb
*.wixobj
*.wixout
*.wixmpp

# Abdeckungsdaten
*.coverage
*.coveragexml

# Roslyn Cache Ordner ausschließen
*Roslyn*/

# VS Code Ordner ausschließen
.vscode/