name: Deploy Swagger Web Service

on:
  push:
    branches:
      - main  # Setzen Sie den Branch, auf dem das Deployment ausgelöst werden soll.
  workflow_dispatch:  # Dies ermöglicht das manuelle Auslösen des Workflows


jobs:
  deploy:
    runs-on: self-hosted  # Stellen Sie sicher, dass dieser Wert auf 'self-hosted' gesetzt ist, um den selbst gehosteten Runner zu nutzen.

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore Dependencies
      run: dotnet restore ZbW_ConnectFour

    - name: Build and Publish
      run: |
        dotnet build ${{ env.Solution_Name }} --configuration Release
        dotnet publish ${{ env.Web_Project_Path }} -c Release -o ./publish --no-restore

    - name: Deploy Service
      run: |
        # Fügen Sie hier Ihre Deployment-Skripte ein, z.B. Kopieren der Dateien zum Server, Neustart des Dienstes etc.
        cp -r ./publish /root/ConnectFour
        cp -r /home/git-runner/actions-runner/_work/ZbW_HF_IT_AuP_2024/ZbW_HF_IT_AuP_2024/Frontend /var/www/public
        cp- r /var/www/public/Frontend/index.html /var/www/public 
        dotnet /root/ConnectFour/publish/ConnectFour.dll

    - name: Clean up
      run: rm -r /root/ConnectFour/publish/*


env:
  Solution_Name: ZbW_ConnectFour
  Web_Project_Path: ZbW_ConnectFour\\ConnectFour
