name: Deploy Swagger Web Service

on:
  push:
    branches:
      - main  # Setzen Sie den Branch, auf dem das Deployment ausgelöst werden soll.
  workflow_dispatch:  # Dies ermöglicht das manuelle Auslösen des Workflows


jobs:
  deploy:
    runs-on: self-hosted  # Stellen Sie sicher, dass dieser Wert auf 'self-hosted' gesetzt ist, um den selbst gehosteten Runner zu nutzen.

    steps:
        
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore Dependencies
      run: dotnet restore ZbW_ConnectFour

    - name: Build and Publish
      run: |
        pkill -f 'ConnectFour.dll' || true
        dotnet build ${{ env.Solution_Name }} --configuration Release
        dotnet publish ${{ env.Web_Project_Path }} -c Release -o ./publish --no-restore

    - name: Deploy Service
      run: |
        # Herstellung einer SSH-Verbindung und Ausführung von Befehlen auf einem Remote-Server
        # ssh root@100.87.201.117 "rm -r /root/ConnectFour/publish/*"
        scp -r ./publish root@100.87.201.117:/root/ConnectFour
        scp -r ./Frontend root@100.87.201.117:/var/www/public
        ssh root@100.87.201.117 "ASPNETCORE_ENVIRONMENT=Production ASPNETCORE_URLS='https://localhost:5001;http://localhost:5000' dotnet /root/ConnectFour/publish/ConnectFour.dll"


    - name: Clean up
      run: |
        ssh root@100.87.201.117 "rm -r /root/ConnectFour/publish/*"
              

env:
  Solution_Name: ZbW_ConnectFour
  Web_Project_Path: ZbW_ConnectFour\\ConnectFour
