name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: [self-hosted]
    steps:
      - uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:git-runner
      - run: mkdir test
